openapi: 3.0.0
info:
  title: API de Carritos
  version: 1.0.0
  description: Documentación de la API para gestión de carritos de compra
  
paths:
  /api/carts:
    post:
      summary: Crea un nuevo carrito
      tags:
        - Carts
      responses:
        '201':
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /api/carts/{id}:
    get:
      summary: Obtiene un carrito por ID
      tags:
        - Carts
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        '200':
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
    put:
      summary: Vacía un carrito por ID
      tags:
        - Carts
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        '200':
          description: Carrito vaciado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
  /api/carts/{id}/purchase:
    post:
      summary: Realiza la compra de un carrito por ID
      tags:
        - Carts
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito
      responses:
        '200':
          description: Compra realizada exitosamente
components:
  schemas:
    Cart:
      type: object
      required:
        - user
        - products
      properties:
        id:
          type: string
          description: ID autogenerado del carrito
        user:
          type: string
          description: ID del usuario asociado con el carrito
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
              quantity:
                type: integer
      example:
        id: d5fE_asz
        user: userId123
        products: [{product: productId123, quantity: 2}]
